//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLoginPage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminLogin
    {
        public int Id { get; set; }

        [DisplayName("E-Posta")]
        [Required(ErrorMessage = "Bu alaný doldurmanýz gerekiyor.")]
        public string eMail { get; set; }

        [DisplayName("Þifre")]
        [Required(ErrorMessage = "Bu alaný doldurmanýz gerekiyor.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
