//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLoginPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
